### ISSUE TITLE
Exporting data in IAGA-2002 format sets NaNs to 88888

### ISSUE THREAD

**Issue by hschovanec-usgs** [usgs/magpy#10]
When data is exported in IAGA-2002 format, the dropped flags (which were set to NaN) are exported as 88888 (https://github.com/usgs/magpy/blob/master/magpy/lib/format_iaga02.py#L476-L489). This is the code for *not observed*. It should instead be 99999, which is the code for *missing data*.

OS: Sierra
MagPy: v0.3.91

**Comment by jmfee-usgs** [comment]
Fixed by #1
