### ISSUE TITLE
Log file causes conflicts when created on a virtual machine

### ISSUE THREAD

**Issue by hschovanec-usgs** [usgs/magpy#2]
MagPy creates a log file in the user's temporary directory by default (https://github.com/usgs/magpy/blob/master/magpy/stream.py#L34). When running on a virtual machine where multiple users have access to the temporary directory, conflicts occur when the file is created by one user, but needs to be accessed by another who does not have write privileges. Only one person at a time can use xmagpy on the virtual machine.

**Comment by jmfee-usgs** [comment]
Fixed by #1 (via environment variables)
