### ISSUE TITLE
Cancel buttons apply changes rather than cancelling

### ISSUE THREAD

**Issue by hschovanec-usgs** [usgs/magpy#3]
Clicking *Cancel* on any gui dialog box will apply the changes or execute the process rather than cancelling in all instances except for the meta page dialog boxes: https://github.com/usgs/magpy/blob/master/magpy/gui/dialogclasses.py#L1641.

**Dialogue boxes needing fix:**
   - [ ] Open File 
   - [ ] Select Directory  
   - [ ] Open URL 
   - [ ] Export Data
   - [ ] Select Active Stream
   - [ ] Basic initialization parameter
   - [ ] Select Columns
   - [ ] Flag Outlier
   - [ ] Flag Selection
   - [ ] Flag Range
   - [ ] Fit
   - [ ] Rotation
   - [ ] Filter
   - [ ] Plot Options

OS: Sierra
MagPy: v0.3.91

**Comment by jmfee-usgs** [comment]
Fixed in #11
