### ISSUE TITLE
Fix conflicting hotkeys

### ISSUE THREAD

**Issue by hschovanec-usgs** [usgs/magpy#31]
There are conflicting hotkeys for menu options. 
`Cmd+I`:
![screen shot 2017-11-22 at 9 26 39 am](https://user-images.githubusercontent.com/26904055/33138304-61be0a10-cf67-11e7-8587-31b3c8a39dce.png)
![screen shot 2017-11-22 at 9 26 51 am](https://user-images.githubusercontent.com/26904055/33138307-62e99b7a-cf67-11e7-86ba-8ee0b72300dc.png)

`Cmd+L `:
![screen shot 2017-11-22 at 9 26 59 am](https://user-images.githubusercontent.com/26904055/33138322-6eab7e4c-cf67-11e7-85df-96ecca04b7c3.png)
![screen shot 2017-11-22 at 9 27 11 am](https://user-images.githubusercontent.com/26904055/33138326-711537c2-cf67-11e7-99dd-f0914b3cf150.png)

**Comment by jmfee-usgs** [comment]
issue submitted to geomagpy/magpy
