### ISSUE TITLE
New favorite URLs are not saved

### ISSUE THREAD

**Issue by hschovanec-usgs** [usgs/magpy#5]
Favorites can be saved in the *Open URL* dialogue box during one session. When the program is closed and reopened, the favorites are not saved. Favorites are read from .magpyguiini, but new favorites are never saved to the file (https://github.com/usgs/magpy/blob/master/magpy/gui/magpy_gui.py#L1698-L1748).

OS: Sierra
MagPy: v0.3.91

**Comment by jmfee-usgs** [comment]
Appears to be fixed in #11
