### ISSUE TITLE
Save log button on Report page does not save a file

### ISSUE THREAD

**Issue by hschovanec-usgs** [usgs/magpy#6]
There is a button to save the log displayed on the Report page, but the button and subsequent dialogue box does not save the log to a file. 
Dialogue box method: https://github.com/usgs/magpy/blob/master/magpy/gui/magpy_gui.py#L3576-L3582 

OS: Sierra
MagPy: v0.3.91

**Comment by jmfee-usgs** [comment]
Appears to be fixed by #11
