### ISSUE TITLE
Extract Values dialogue will not close without choosing the Extract button

### ISSUE THREAD

**Issue by hschovanec-usgs** [usgs/magpy#7]
In the *Extract Values* dialog box on the **Stream** page, choosing *Cancel* or *x* has no effect. The only way to close the box is to choose *Extract*. Tied to issue #3. 
Dialogue box class: https://github.com/usgs/magpy/blob/master/magpy/gui/dialogclasses.py#L885-L988

OS: Sierra
MagPy: v0.3.91

**Comment by jmfee-usgs** [comment]
Fixed by #11
