### ISSUE TITLE
Entering out of order dates disables all controls 

### ISSUE THREAD

**Issue by hschovanec-usgs** [usgs/magpy#8]
Entering out of order dates on the **Stream** page and choosing *Trim timerange* will disable all controls. Controls are only enables when a new file or URL is loaded.
Trim time range method: https://github.com/usgs/magpy/blob/master/magpy/gui/magpy_gui.py#L2563-L2599

OS: Sierra
MagPy: v0.3.91

**Comment by jmfee-usgs** [comment]
Fixed by #11
